---
exclude: ['README.markdown', 'Makefile', 'component.json']
pygments: true
safe: false

name: devo.ps
# url: http://devo.ps
author: devo.ps
email: info@devo.ps
ga: 'UA-34006371-1'
gauges: '510b396a613f5d2666000007'
# mixpanel: '7b7a659fc843818d4c523cde96863ef5'