---
exclude: ['README.markdown', 'Makefile', 'component.json']
pygments: true
safe: false

name: Foundation
# url: http://wiredcraft.github.com/foundation
author: devo.ps
email: info@devo.ps
ga: 'UA-XXXXXXX-X'